### ISSUE TITLE
Create login page

### ISSUE THREAD

**Issue by chanti1994** [chanti1994/Login-App#1]
1. Create a **login screen** with **two text input fields**
2. Create a **Login Button** for confirmation**
 
![image](https://github.com/chanti1994/Login-App/assets/127018627/e818ee90-61b5-482f-ac0f-1c110fb66173)

**Comment by sandeepamdocs** [comment]
![image](https://github.com/chanti1994/Login-App/assets/161006075/bce1e950-42d9-413c-b897-251bf47ebe46)
Final done.........
